import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { FlexLayoutModule } from '@angular/flex-layout';

import { 
  MatMenuModule,
  MatCardModule,
  MatLineModule,
  MatListModule,
  MatSortModule,
  MatTreeModule,
  MatBadgeModule,
  MatChipsModule,
  MatInputModule,
  MatRadioModule,
  MatTableModule,
  MatCommonModule,
  MatDialogModule,
  MatOptionModule,
  MatRippleModule,
  MatSelectModule,
  MatSliderModule,
  MatDividerModule,
  MatStepperModule,
  MatTooltipModule,
  MatCheckboxModule,
  MatGridListModule,
  MatSnackBarModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatBottomSheetModule,
  MatProgressBarModule,
  MatSlideToggleModule,
  MatAutocompleteModule,
  MatButtonToggleModule,
  MatPseudoCheckboxModule,
  MatIconModule,
  MatToolbarModule,
  MatButtonModule,
  MatFormFieldModule,
  MatSidenavModule,
  MatTabsModule,
  MatProgressSpinnerModule
} from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  imports:      [ 
    BrowserModule, 
    BrowserAnimationsModule, 
    FormsModule,
    ReactiveFormsModule,
    FlexLayoutModule,

    MatMenuModule,
    MatCardModule,
    MatLineModule,
    MatListModule,
    MatSortModule,
    MatTreeModule,
    MatBadgeModule,
    MatChipsModule,
    MatInputModule,
    MatRadioModule,
    MatTableModule,
    MatCommonModule,
    MatDialogModule,
    MatOptionModule,
    MatRippleModule,
    MatSelectModule,
    MatSliderModule,
    MatDividerModule,
    MatStepperModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatBottomSheetModule,
    MatProgressBarModule,
    MatSlideToggleModule,
    MatAutocompleteModule,
    MatButtonToggleModule,
    MatPseudoCheckboxModule,
    MatIconModule,
    MatToolbarModule,
    MatButtonModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatTabsModule,
    MatProgressSpinnerModule
  ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
